name: Python Tests

on:
  push:
    branches:
      - main
      - Github-Actions
  pull_request:
    branches:
      - main
      - Github-Actions
  workflow_dispatch:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1
      - name: Set up Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov
          pip install -r requirements.txt

      - name: Run pytest
        run: |
          pytest --cov=navier_stokes_fdm --cov-report=xml
